/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas2
     */
    public Tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brg1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        brg2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brg3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasl = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 100, 20);

        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 120, 14);
        getContentPane().add(brg1);
        brg1.setBounds(180, 40, 150, 30);

        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 120, 14);
        getContentPane().add(brg2);
        brg2.setBounds(180, 80, 150, 30);

        jLabel4.setText("Total Bayar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 120, 14);
        getContentPane().add(brg3);
        brg3.setBounds(180, 120, 150, 30);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 120, 14);
        getContentPane().add(dis);
        dis.setBounds(180, 160, 30, 30);

        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(130, 210, 90, 40);

        hasl.setColumns(20);
        hasl.setRows(5);
        jScrollPane1.setViewportView(hasl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 300, 120);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("%");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 160, 40, 30);

        jLabel7.setText("Harga Barang 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 130, 120, 14);

        setBounds(0, 0, 389, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int Bar1 = Integer.parseInt(brg1.getText());
        int Bar2 = Integer.parseInt(brg2.getText());
        int Bar3 = Integer.parseInt(brg3.getText());
        int Dis = Integer.parseInt(dis.getText());
        if (Dis==0)
            Dis = 100;
        int total = Bar1+Bar2+Bar3;
        int Diskon = Bar1 * Dis / 100 + Bar2 * Dis / 100 + Bar3 * Dis / 100;
        
        hasl.setText("Harga Barang 1 = "+Bar1+"\nHarga Barang 2 = "+Bar2+"\nHarga Barang 3 = "+Bar3+"\nHarga Total = "+total+"\nDiskon = "+Dis+"%\nJumlah Bayar = "+Diskon+"\n");
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField dis;
    private javax.swing.JTextArea hasl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
